
#1.首先本机Host文件加上（重要）：127.0.0.1  peer1 peer2 peer3
 # PS：这里连接Eureka服务器的时候采用Host跳转的方式，实际发布的时候将peer替换成网络域名或真实IP就可以了

#2.启动方式（重要）：在IDEA -> Run Configuration-> SpringBoot - Active Profiles  启动三个项目实例 分别指定eureka-peer1 2 3

#EurekaServer-公共配置
spring:
  application:
    name: Eureka-HA

---
#EurekaServer-节点1
spring:
  profiles: eureka-peer1  #profile 名称 用于启动项目的时候从多个文件中加载指定配置文件
server:
  port: 8761 #节点端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/  #指定服务器EurekaServer
---
#EurekaServer-节点2
spring:
  profiles: eureka-peer2
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
---
#EurekaServer-节点3
spring:
  profiles: eureka-peer3
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
